version: '3.7'

x-labels:
  &default-label
  labels:
    - "proxy"
x-volumes:
  &default-volumes
  volumes:
    - certs:/etc/nginx/certs
    - conf:/etc/nginx/conf.d
    - vhost:/etc/nginx/vhost.d
    - html:/usr/share/nginx/html
    - dhparam:/etc/nginx/dhparam
    - /var/run/docker.sock:/var/run/docker.sock:ro

services:
  proxy:
    build: ./proxy
    container_name: proxy
    << : *default-label
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    ports:
      - 80:80
      - 443:443
    << : *default-volumes
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy_le
    << : *default-label
    restart: always
    << : *default-volumes
    depends_on:
      - proxy
    networks:
      - proxy-tier

volumes:
  conf: *default-label
  dhparam: *default-label
  certs: *default-label
  vhost: *default-label
  html: *default-label

networks:
  proxy-tier:
    name: proxy-tier
