version: '3.7'

x-labels: 
  labels: &default-label
    proxy:

services:
  proxy:
    build: ./proxy
    container_name: proxy
    labels:
      <<: *default-label
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy_le
    labels: *default-label
    restart: always
    volumes: 
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    networks:
      - proxy-tier

volumes:
  conf:
    labels: *default-label
  dhparam:
    labels: *default-label
  certs:
    labels: *default-label
  vhost:
    labels: *default-label
  html:
    labels: *default-label

networks:
  proxy-tier:
    name: proxy-tier
