version: '3.7'

x-volumes:
  &default-volume
  labels:
    - "proxy"

services:
  proxy:
    build: ./proxy
    container_name: proxy
    << : *default-volume
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy_le
    << : *default-volume
    restart: always
    volumes:
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    networks:
      - proxy-tier

volumes:
  conf: *default-volume
  dhparam: *default-volume
  certs: *default-volume
  vhost: *default-volume
  html: *default-volume

networks:
  proxy-tier:
    name: proxy-tier
