version: '3.7'

x-labels: 
  labels: &default-label
    proxy:

services:
  nginx-proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: always
    labels:
      <<: *default-label
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    depends_on:
      - nginx-proxy
    restart: always
    labels:
      <<: *default-label
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen:
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - proxy-tier

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
      - docker-gen
    labels: *default-label
    env_file:
      - .env
    volumes: 
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

volumes:
  conf:
    labels: *default-label
  vhost:
    labels: *default-label
  html:
    labels: *default-label
  certs:
    labels: *default-label
  acme:
    labels: *default-label

networks:
  proxy-tier:
    name: proxy-tier
